@startuml

title __SIMIAN's Class Diagram__\n

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace dry {
          namespace simian {
            class edu.hm.hafner.analysis.parser.dry.simian.Block {
                - endLineNumber : int
                - sourceFile : String
                - startLineNumber : int
                + getEndLineNumber()
                + getSourceFile()
                + getStartLineNumber()
                + setEndLineNumber()
                + setSourceFile()
                + setStartLineNumber()
            }
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace dry {
          namespace simian {
            class edu.hm.hafner.analysis.parser.dry.simian.Set {
                - blocks : List<Block>
                - lineCount : int
                + addBlock()
                + getBlocks()
                + getLineCount()
                + setLineCount()
            }
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace dry {
          namespace simian {
            class edu.hm.hafner.analysis.parser.dry.simian.SimianParser {
                {static} - serialVersionUID : long
                + SimianParser()
                + SimianParser()
                # configureParser()
                # convertDuplicationsToIssues()
            }
          }
        }
      }
    }
  }
  

  edu.hm.hafner.analysis.parser.dry.simian.SimianParser -up-|> edu.hm.hafner.analysis.parser.dry.AbstractDryParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
