package edu.hm.hafner.analysis.registry;

import java.util.Collection;

import edu.hm.hafner.analysis.IssueParser;
import edu.hm.hafner.analysis.parser.Gcc4Cc1Parser;
import edu.hm.hafner.analysis.parser.Gcc4CompilerParser;
import edu.hm.hafner.analysis.parser.Gcc4LinkerParser;

/**
 * A descriptor for the GNU C Compiler (gcc).
 *
 * <p>
 * Supports GCC version 4 and newer, including modern versions up to GCC 15+.
 * This parser handles the standard GCC output format introduced in GCC 4.
 * </p>
 *
 * <p>
 * For legacy GCC versions (pre-GCC 4), use the "gcc3" parser instead.
 * </p>
 *
 * @author Lorenz Munsch
 */
class Gcc4Descriptor extends CompositeParserDescriptor {
    private static final String ID = "gcc";
    private static final String NAME = "GNU C Compiler (GCC)";

    Gcc4Descriptor() {
        super(ID, NAME);
    }

    @Override
    protected Collection<? extends IssueParser> createParsers() {
        return asList(new Gcc4CompilerParser(), new Gcc4LinkerParser(), new Gcc4Cc1Parser());
    }

    @Override
    public String getHelp() {
        return "<p>Parses warnings and errors generated by GCC version 4 and newer "
                + "(including GCC 5–15+). Use this parser for modern GCC compilers "
                + "that output messages in the standard format like:</p>"
                + "<p><code>file.c:10:5: warning: unused variable 'x' [-Wunused-variable]</code></p>"
                + "<p>For very old GCC versions (pre-GCC 4), use the 'gcc3' parser instead.</p>";
    }
}
