package edu.hm.hafner.analysis.registry;

import edu.hm.hafner.analysis.IssueParser;
import edu.hm.hafner.analysis.Report.IssueType;
import edu.hm.hafner.analysis.parser.PrismaCloudParser;

/**
 * A descriptor for Prisma Cloud (Twistlock) container image scan reports generated by {@code twistcli}.
 *
 * @author Akash Manna
 * @see <a href="https://www.paloaltonetworks.com/prisma/cloud">Prisma Cloud</a>
 */
class PrismaCloudDescriptor extends ParserDescriptor {
    private static final String ID = "prisma-cloud";
    private static final String NAME = "Prisma Cloud";

    PrismaCloudDescriptor() {
        super(ID, NAME);
    }

    @Override
    public IssueType getType() {
        return IssueType.VULNERABILITY;
    }

    @Override
    public IssueParser create(final Option... options) {
        return new PrismaCloudParser();
    }

    @Override
    public String getPattern() {
        return "**/prisma-cloud-report.json";
    }

    @Override
    public String getHelp() {
        return "Use commandline <code>twistcli images scan --output-file prisma-cloud-report.json &lt;IMAGE&gt;</code>"
                + " to generate JSON output.<br/>"
                + "See <a href='https://docs.prismacloud.io/en/enterprise-edition/content-collections/runtime-security/tools/twistcli-scan-images'>"
                + "twistcli documentation</a> for usage details.";
    }

    @Override
    public String getUrl() {
        return "https://www.paloaltonetworks.com/prisma/cloud";
    }

    @Override
    public String getIconUrl() {
        return "https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/docs/api/cdn/prisma-cloud-logo.png?raw=true";
    }
}
