@startuml
LineRangeTest -> SerializableTest: createSerializable()
SerializableTest -> LineRange: new LineRange()
LineRange -> SerializableTest: return instanceof LineRange
SerializableTest --> SerializableTest : LineRange to byteArray
SerializableTest --> SerializableTest : byteArray to LineRange
SerializableTest -> LineRangeTest : return result
@enduml