@startuml

title __CHECKSTYLE's Class Diagram__\n

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace checkstyle {
          class edu.hm.hafner.analysis.parser.checkstyle.CheckStyle {
              - files : List<File>
              + addFile()
              + getFiles()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace checkstyle {
          class edu.hm.hafner.analysis.parser.checkstyle.CheckStyleParser {
              {static} - serialVersionUID : long
              + parse()
              - convert()
              - getCategory()
              - getType()
              - isValidWarning()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace checkstyle {
          class edu.hm.hafner.analysis.parser.checkstyle.Error {
              - column : int
              - line : int
              - message : String
              - severity : String
              - source : String
              + getColumn()
              + getLine()
              + getMessage()
              + getSeverity()
              + getSource()
              + setColumn()
              + setLine()
              + setMessage()
              + setSeverity()
              + setSource()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace checkstyle {
          class edu.hm.hafner.analysis.parser.checkstyle.File {
              - errors : List<Error>
              - name : String
              + addError()
              + getErrors()
              + getName()
              + setName()
          }
        }
      }
    }
  }
  

  edu.hm.hafner.analysis.parser.checkstyle.CheckStyleParser -up-|> edu.hm.hafner.analysis.IssueParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
