@startuml

class LineRangeTest {
    # createSeriailzable(): LineRange
}

class SerializableTest <<abstract>>

class LineRange

interface Serializable

LineRange ..|> Serializable
LineRangeTest --* LineRange
LineRangeTest -|> SerializableTest

@enduml