@startuml

title Factorypattern

class SerializableTest<LineRange>
interface Serializable{}
class LineRange{}
class LineRangeTest{
    LineRange : createSerializable
}

LineRange --|> Serializable : implements
LineRangeTest ..> SerializableTest : extends
LineRangeTest --> LineRange : uses

@enduml