@startuml

interface Serializable
abstract class "SerializableTest<LineRange>"
LineRangeTest --|> "SerializableTest<LineRange>" : extends
"SerializableTest<LineRange>" --|> Serializable :extends
"SerializableTest<LineRange>" --|> LineRange: creates
LineRange --|>Serializable

@enduml
