@startuml

SerializableTest -> LineRangeTest: createSerializable()
LineRangeTest -> SerializableTest: LineRange

SerializableTest -> LineRangeTest: createSerializable()
LineRangeTest -> SerializableTest: LineRange

SerializableTest -> LineRangeTest: createSerializable()
LineRangeTest -> SerializableTest: LineRange

SerializableTest -> LineRangeTest: createSerializable()
LineRangeTest -> SerializableTest: LineRange

@enduml