@startuml

title Factory Pattern Klassendiagramm

class LineRange
class LineRangeTest
interface Serializable
abstract class SerializableTest

SerializableTest <|-- LineRangeTest : <<extends>>
LineRange ..|> Serializable : <<implements>>
LineRangeTest ..> LineRange : <<tests>>
Serializable <|.. SerializableTest : <<creates>>

@enduml