@startuml
title IssueFilerBuilder UML Diagram

class IssueFilterBuilder
class IssueFilterTest
class Report

Report <-- Issue : contains
Report <-- IssueFilterBuilder : builds filters for Issues
IssueFilterTest --> IssueFilterBuilder :uses

@enduml