@startuml

create LineRange
activate LineRange

create LineRangeTest
activate LineRangeTest

create SerializableTest
activate SerializableTest

create Serializable
activate Serializable

SerializableTest -> Serializable : new Serializable<LineRange>()
Serializable -> LineRangeTest : createSerializable()
LineRangeTest --> LineRange : new LineRange()

@enduml