@startuml

abstract class "SerializableTest<LineRange>"
interface Serializable

LineRangeTest --|> "SerializableTest<LineRange>"
LineRange --|> Serializable
"SerializableTest<LineRange>" ..> LineRange

@enduml