@startuml

User -> LineRangeTest: shouldBeSerializable()
LineRangeTest -> SerializableTest: shouldBeSerializable()
SerializableTest -> LineRangeTest: createSerializable()
LineRangeTest -> LineRange: new LineRange()<Serializable>
LineRange --> LineRangeTest: LineRange()<Serializable>
LineRangeTest --> SerializableTest: createSerializable()
SerializableTest -> SerializableTest: toByteArray()
SerializableTest --> User: shouldBeSerializable()

@enduml