@startuml

hide circle

class LineRange {}
class SerializableTest<LineRange> {
    {abstract} #createSerializable()
}
interface Serializable {}
class LineRangeTest {
    #createSerializable()
}

Serializable <|-- LineRange
SerializableTest <|-- LineRangeTest

SerializableTest ..> Serializable
LineRangeTest ..> LineRange

@enduml