@startuml

JUnit -> SerializableTest : create Serializable

SerializableTest -> LineRangeTest : create Serializable for LineRange

LineRangeTest -> LineRangeTest : createFilledLineRange()

SerializableTest <-- LineRangeTest

JUnit <-- SerializableTest

@enduml