@startuml

title LineRangeTest Klassendiagramm

abstract class SerializableTest
class LineRangeTest
interface Serializable

SerializableTest <|-- LineRangeTest : <<extends>>
LineRange <.. LineRangeTest : << tests >>
Serializable <|.. LineRange : <<implements>>
Serializable <.. SerializableTest : <<creates>>

@enduml