@startuml

title __CPD's Class Diagram__\n

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace dry {
          namespace cpd {
            class edu.hm.hafner.analysis.parser.dry.cpd.CpdParser {
                {static} - serialVersionUID : long
                + CpdParser()
                + CpdParser()
                # configureParser()
                # convertDuplicationsToIssues()
            }
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace dry {
          namespace cpd {
            class edu.hm.hafner.analysis.parser.dry.cpd.Duplication {
                - codeFragment : String
                - files : List<SourceFile>
                - lines : int
                - tokens : int
                + addFile()
                + getCodeFragment()
                + getFiles()
                + getLines()
                + getTokens()
                + setCodeFragment()
                + setLines()
                + setTokens()
            }
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace dry {
          namespace cpd {
            class edu.hm.hafner.analysis.parser.dry.cpd.SourceFile {
                - line : int
                - path : String
                + getLine()
                + getPath()
                + setLine()
                + setPath()
            }
          }
        }
      }
    }
  }
  

  edu.hm.hafner.analysis.parser.dry.cpd.CpdParser -up-|> edu.hm.hafner.analysis.parser.dry.AbstractDryParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
