@startuml

title __JCREPORT's Class Diagram__\n

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace jcreport {
          class edu.hm.hafner.analysis.parser.jcreport.File {
              - classname : String
              - items : List<Item>
              - level : String
              - loc : String
              - name : String
              - packageName : String
              - srcdir : String
              + addItem()
              + getClassname()
              + getItems()
              + getLevel()
              + getLoc()
              + getName()
              + getPackageName()
              + getSrcdir()
              + setClassname()
              + setLevel()
              + setLoc()
              + setName()
              + setPackageName()
              + setSrcdir()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace jcreport {
          class edu.hm.hafner.analysis.parser.jcreport.Item {
              - column : String
              - endcolumn : String
              - endline : String
              - findingtype : String
              - line : String
              - message : String
              - origin : String
              - severity : String
              + getColumn()
              + getEndcolumn()
              + getEndline()
              + getFindingtype()
              + getLine()
              + getMessage()
              + getOrigin()
              + getSeverity()
              + setColumn()
              + setEndcolumn()
              + setEndline()
              + setFindingtype()
              + setLine()
              + setMessage()
              + setOrigin()
              + setSeverity()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace jcreport {
          class edu.hm.hafner.analysis.parser.jcreport.JcReportParser {
              {static} - serialVersionUID : long
              + createReport()
              + parse()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace jcreport {
          class edu.hm.hafner.analysis.parser.jcreport.Report {
              - files : List<File>
              + addFile()
              + getFiles()
              + setFiles()
          }
        }
      }
    }
  }
  

  edu.hm.hafner.analysis.parser.jcreport.JcReportParser -up-|> edu.hm.hafner.analysis.IssueParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
