package edu.hm.hafner.analysis.parser;

import org.json.JSONArray;
import org.json.JSONObject;

import edu.hm.hafner.analysis.Issue;
import edu.hm.hafner.analysis.IssueBuilder;
import edu.hm.hafner.analysis.Report;

import java.io.Serial;

/**
 * A parser for Prisma Cloud (Twistlock) container image scan JSON reports, generated by {@code twistcli}.
 *
 * @author Akash Manna
 * @see <a href="https://www.paloaltonetworks.com/prisma/cloud">Prisma Cloud</a>
 * @see <a href="https://docs.prismacloud.io/en/enterprise-edition/content-collections/runtime-security/tools/twistcli-scan-images">
 *     twistcli documentation</a>
 */
public class PrismaCloudParser extends JsonIssueParser {
    @Serial
    private static final long serialVersionUID = 8528108766279887313L;

    private static final String RESULTS_KEY = "results";
    private static final String VULNERABILITIES_KEY = "vulnerabilities";
    private static final String COMPLIANCES_KEY = "compliances";

    private static final String VULN_ID_KEY = "id";
    private static final String VULN_SEVERITY_KEY = "severity";
    private static final String VULN_DESCRIPTION_KEY = "description";
    private static final String VULN_PACKAGE_NAME_KEY = "packageName";
    private static final String VULN_PACKAGE_VERSION_KEY = "packageVersion";
    private static final String VULN_LINK_KEY = "link";
    private static final String VULN_CVSS_KEY = "cvss";
    private static final String VULN_VECTOR_KEY = "vector";
    private static final String VULN_RISK_FACTORS_KEY = "riskFactors";

    private static final String COMPLIANCE_ID_KEY = "id";
    private static final String COMPLIANCE_TITLE_KEY = "title";
    private static final String COMPLIANCE_SEVERITY_KEY = "severity";
    private static final String COMPLIANCE_DESCRIPTION_KEY = "description";
    private static final String COMPLIANCE_CAUSE_KEY = "cause";

    private static final String ENTITY_INFO_KEY = "entityInfo";
    private static final String ENTITY_NAME_KEY = "name";

    @Override
    protected void parseJsonArray(final Report report, final JSONArray jsonReport, final IssueBuilder issueBuilder) {
        for (int i = 0; i < jsonReport.length(); i++) {
            var scanResult = jsonReport.optJSONObject(i);
            if (scanResult != null) {
                parseScanResult(report, scanResult, issueBuilder);
            }
        }
    }

    private void parseScanResult(final Report report, final JSONObject scanResult, final IssueBuilder issueBuilder) {
        var imageName = extractImageName(scanResult);
        var results = scanResult.optJSONArray(RESULTS_KEY);
        if (results == null) {
            return;
        }

        for (int i = 0; i < results.length(); i++) {
            var result = results.optJSONObject(i);
            if (result != null) {
                parseVulnerabilities(report, result.optJSONArray(VULNERABILITIES_KEY), imageName, issueBuilder);
                parseCompliances(report, result.optJSONArray(COMPLIANCES_KEY), imageName, issueBuilder);
            }
        }
    }

    private String extractImageName(final JSONObject scanResult) {
        var entityInfo = scanResult.optJSONObject(ENTITY_INFO_KEY);
        if (entityInfo != null) {
            return entityInfo.optString(ENTITY_NAME_KEY, "-");
        }
        return "-";
    }

    private void parseVulnerabilities(final Report report, final JSONArray vulnerabilities,
            final String imageName, final IssueBuilder issueBuilder) {
        if (vulnerabilities == null) {
            return;
        }

        for (int i = 0; i < vulnerabilities.length(); i++) {
            var vuln = vulnerabilities.optJSONObject(i);
            if (vuln != null) {
                report.add(convertVulnerabilityToIssue(vuln, imageName, issueBuilder));
            }
        }
    }

    private Issue convertVulnerabilityToIssue(final JSONObject vuln, final String imageName,
            final IssueBuilder issueBuilder) {
        var cveId = vuln.optString(VULN_ID_KEY, "-");
        var packageName = vuln.optString(VULN_PACKAGE_NAME_KEY, "-");
        var packageVersion = vuln.optString(VULN_PACKAGE_VERSION_KEY, "");
        var packageLabel = packageVersion.isEmpty() ? packageName : packageName + "@" + packageVersion;
        var description = buildVulnerabilityDescription(vuln, packageName, packageVersion);

        return issueBuilder
                .setType(cveId)
                .setMessage(vuln.optString(VULN_DESCRIPTION_KEY, cveId))
                .guessSeverity(vuln.optString(VULN_SEVERITY_KEY, "medium"))
                .setFileName(imageName)
                .setPackageName(packageLabel)
                .setCategory("Vulnerability")
                .setDescription(description)
                .buildAndClean();
    }

    private String buildVulnerabilityDescription(final JSONObject vuln, final String packageName,
            final String packageVersion) {
        var sb = new StringBuilder();

        var description = vuln.optString(VULN_DESCRIPTION_KEY, "");
        if (!description.isBlank()) {
            sb.append("<p>").append(description).append("</p>");
        }

        var cvss = vuln.optDouble(VULN_CVSS_KEY, -1);
        if (cvss >= 0) {
            sb.append("<p><strong>CVSS Score:</strong> ").append(cvss).append("</p>");
        }

        var vector = vuln.optString(VULN_VECTOR_KEY, "");
        if (!vector.isBlank()) {
            sb.append("<p><strong>CVSS Vector:</strong> ").append(vector).append("</p>");
        }

        if (!packageName.isBlank()) {
            sb.append("<p><strong>Package:</strong> ").append(packageName);
            if (!packageVersion.isBlank()) {
                sb.append(" @ ").append(packageVersion);
            }
            sb.append("</p>");
        }

        var link = vuln.optString(VULN_LINK_KEY, "");
        if (!link.isBlank()) {
            sb.append("<p><strong>Reference:</strong> <a href=\"").append(link).append("\">").append(link)
                    .append("</a></p>");
        }

        var riskFactors = vuln.optJSONArray(VULN_RISK_FACTORS_KEY);
        var riskFactorsDescription = buildJsonArrayDescription(riskFactors, "Risk Factors");
        if (!riskFactorsDescription.isBlank()) {
            sb.append(riskFactorsDescription);
        }

        return sb.toString();
    }

    private void parseCompliances(final Report report, final JSONArray compliances,
            final String imageName, final IssueBuilder issueBuilder) {
        if (compliances == null) {
            return;
        }

        for (int i = 0; i < compliances.length(); i++) {
            var compliance = compliances.optJSONObject(i);
            if (compliance != null) {
                report.add(convertComplianceToIssue(compliance, imageName, issueBuilder));
            }
        }
    }

    private Issue convertComplianceToIssue(final JSONObject compliance, final String imageName,
            final IssueBuilder issueBuilder) {
        var id = String.valueOf(compliance.optInt(COMPLIANCE_ID_KEY, 0));
        var title = compliance.optString(COMPLIANCE_TITLE_KEY, "-");
        var description = buildComplianceDescription(compliance);

        return issueBuilder
                .setType(id)
                .setMessage(title)
                .guessSeverity(compliance.optString(COMPLIANCE_SEVERITY_KEY, "medium"))
                .setFileName(imageName)
                .setCategory("Compliance")
                .setDescription(description)
                .buildAndClean();
    }

    private String buildComplianceDescription(final JSONObject compliance) {
        var sb = new StringBuilder();

        var description = compliance.optString(COMPLIANCE_DESCRIPTION_KEY, "");
        if (!description.isBlank()) {
            sb.append("<p>").append(description).append("</p>");
        }

        var cause = compliance.optString(COMPLIANCE_CAUSE_KEY, "");
        if (!cause.isBlank()) {
            sb.append("<p><strong>Cause:</strong> ").append(cause).append("</p>");
        }

        return sb.toString();
    }
}
