@startuml

title __CCM's Class Diagram__\n

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace ccm {
          class edu.hm.hafner.analysis.parser.ccm.Ccm {
              - metrics : List<Metric>
              + addMetric()
              + getMetrics()
              + setMetrics()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace ccm {
          class edu.hm.hafner.analysis.parser.ccm.CcmParser {
              {static} - serialVersionUID : long
              + parse()
              - calculateMetricPriority()
              - convert()
              - isMetricHighPriority()
              - isMetricModeratePriority()
              - parseCCMXmlFile()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace ccm {
          class edu.hm.hafner.analysis.parser.ccm.Metric {
              - classification : String
              - complexity : int
              - endLineNumber : int
              - file : String
              - startLineNumber : int
              - unit : String
              + getClassification()
              + getComplexity()
              + getEndLineNumber()
              + getFile()
              + getStartLineNumber()
              + getUnit()
              + setClassification()
              + setComplexity()
              + setEndLineNumber()
              + setFile()
              + setStartLineNumber()
              + setUnit()
          }
        }
      }
    }
  }
  

  edu.hm.hafner.analysis.parser.ccm.CcmParser -up-|> edu.hm.hafner.analysis.IssueParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
