@startuml

title __PMD's Class Diagram__\n

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace pmd {
          class edu.hm.hafner.analysis.parser.pmd.File {
              - name : String
              - violations : List<Violation>
              + addViolation()
              + getName()
              + getViolations()
              + setName()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace pmd {
          class edu.hm.hafner.analysis.parser.pmd.Pmd {
              - errors : List<PmdError>
              - files : List<File>
              + addError()
              + addFile()
              + getErrors()
              + getFiles()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace pmd {
          class edu.hm.hafner.analysis.parser.pmd.PmdError {
              - description : String
              - filename : String
              - msg : String
              + getDescription()
              + getFilename()
              + getMsg()
              + setDescription()
              + setFilename()
              + setMsg()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace pmd {
          class edu.hm.hafner.analysis.parser.pmd.PmdParser {
              {static} - PMD_PRIORITY_MAPPED_TO_HIGH_PRIORITY : int
              {static} - PMD_PRIORITY_MAPPED_TO_LOW_PRIORITY : int
              {static} - serialVersionUID : long
              + parse()
              - convertErrors()
              - convertIssues()
              - createMessage()
              - mapPriority()
              - parseErrors()
              - parseIssues()
          }
        }
      }
    }
  }
  

  namespace edu.hm.hafner {
    namespace analysis {
      namespace parser {
        namespace pmd {
          class edu.hm.hafner.analysis.parser.pmd.Violation {
              - begincolumn : int
              - beginline : int
              - endcolumn : int
              - endline : int
              - externalInfoUrl : String
              - javaPackage : String
              - message : String
              - priority : int
              - rule : String
              - ruleset : String
              + getBegincolumn()
              + getBeginline()
              + getEndcolumn()
              + getEndline()
              + getExternalInfoUrl()
              + getMessage()
              + getPackage()
              + getPriority()
              + getRule()
              + getRuleset()
              + setBegincolumn()
              + setBeginline()
              + setEndcolumn()
              + setEndline()
              + setExternalInfoUrl()
              + setMessage()
              + setPackage()
              + setPriority()
              + setRule()
              + setRuleset()
          }
        }
      }
    }
  }
  

  edu.hm.hafner.analysis.parser.pmd.PmdParser -up-|> edu.hm.hafner.analysis.IssueParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
