name: Sync labels
on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
